Change some fields to M-M in Film class
umsi-arwhyte/gffa pull request #31
Opened 2020-11-20 19:05 UTC by cunzhig

- Changed field `people` to `characters` in Film
- Changed `characters`, `planets`, `starships`, `vehicles` and `species` from M-O to M-M
- Added `get_characters`, `get_planets`, `get_starships`, `get_vehicles` and `get_species` in Film model since `list_display` in admin.py doesn't support ManyToManyField. Those functions will display a list of corresponding urls in each field.

Related issue #26

2020-11-20 22:42 UTC, arwhyte requested changes
Add "join" tables to the model.

2020-11-20 22:42 UTC, arwhyte commented on apps/webapp/models.py
> +    characters = models.ManyToManyField('Person', related_name="film_people", blank=True)
Looking ahead I'd prefer that we define the "join" table explicitly rather than rely on Django to define it implicitly.  We need a new model: `FilmPerson`

Fields:
```python
film_person_id = models.AutoField(primary_key=True)   <--NOTE: Try first to create FilmPerson without this AutoField
film = models.ForeignKey(Film, on_delete=models.CASCADE)
person = models.ForeignKey(Person, on_delete=models.CASCADE)
```

Then adjust the `Film` model:

```python
characters = models.ManyToManyField(Person, through='FilmPerson', related_name='film_person', blank=True)
```

Then do the same for the M-M relationships:

New models:

`FilmPlanet`
`FilmStarship`
`FilmVehicle`

Then adjust the Film model.

We need to do this for other M-M relationships.

2020-12-03 18:12 UTC, cunzhig commented on apps/webapp/models.py
> +    characters = models.ManyToManyField('Person', related_name="film_people", blank=True)
Added FilmPerson model. New film can not be added after new changes.

2020-12-04 02:38 UTC, arwhyte commented on apps/api/serializers.py
> +    id = serializers.ReadOnlyField(source='film.id')
should `source=film_id` ??

2020-12-11 13:34 UTC, merged